setw -g mode-keys vi
# unbind C-b
# set-option -g prefix C-v
# bind-key C-v send-prefix
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
# For binding 'y' to copy and exiting selection mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'

# For binding 'Enter' to copy and not leave selection mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe 'xclip -sel clip -i' '\;'  send -X clear-selection

# Set the control character to Ctrl+Spacebar (instead of Ctrl+B)
set -g prefix C-space
# unbind-key C-b
bind-key C-space send-prefix

# Set new panes to open in current directory
# bind c new-window -c "#{pane_current_path}"
# bind '"' split-window -v -c "#{pane_current_path}"
# bind % split-window -h -c "#{pane_current_path}"
bind-key j command-prompt -p "join pane from (session:window.pane):" "join-pane -s '%%'"
bind-key k "break-pane"
bind-key J command-prompt -p "move window to session:" "run-shell \"tmux has-session -t '%1:' 2>/dev/null && tmux move-window -t '%1:' || { S=$(tmux new-session -d -P -F \"#S\"); tmux move-window -t \"\$S:\"; }\""
bind-key K command-prompt -p "pull window from (session:window):" "run-shell \"tmux move-window -s '%1' -t '#S:'\""
set -g history-limit 10000
